Started GET "/" for 192.168.32.1 at 2023-08-09 10:47:53 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 9.2ms | Allocations: 404)
Completed 200 OK in 41ms (Views: 18.6ms | ActiveRecord: 0.0ms | Allocations: 3441)


Started GET "/ws" for 192.168.32.1 at 2023-08-09 10:47:55 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.32.1 at 2023-08-09 10:47:56 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.32.1 at 2023-08-09 10:47:59 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.32.1 at 2023-08-09 10:48:04 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.48.1 at 2023-08-09 10:50:22 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.48.1 at 2023-08-09 10:50:22 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 192.168.48.1 at 2023-08-09 10:50:23 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 5.8ms | Allocations: 182)
Completed 200 OK in 14ms (Views: 10.1ms | ActiveRecord: 0.0ms | Allocations: 1665)


Started GET "/" for 192.168.48.1 at 2023-08-09 10:50:23 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 10.7ms | Allocations: 177)
Completed 200 OK in 14ms (Views: 12.7ms | ActiveRecord: 0.0ms | Allocations: 712)


Started GET "/" for 192.168.48.1 at 2023-08-09 10:50:24 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 0.6ms | Allocations: 7)
Completed 200 OK in 3ms (Views: 2.3ms | ActiveRecord: 0.0ms | Allocations: 235)


Started GET "/ws" for 192.168.80.1 at 2023-08-09 12:34:09 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 192.168.80.1 at 2023-08-09 12:34:10 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 9.4ms | Allocations: 182)
Completed 200 OK in 16ms (Views: 10.9ms | ActiveRecord: 0.0ms | Allocations: 1665)


Started GET "/" for 192.168.80.1 at 2023-08-09 12:34:11 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 13.4ms | Allocations: 178)
Completed 200 OK in 17ms (Views: 15.5ms | ActiveRecord: 0.0ms | Allocations: 718)


Started GET "/" for 192.168.96.1 at 2023-08-09 12:39:59 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 3.5ms | Allocations: 297)
Completed 200 OK in 8ms (Views: 5.4ms | ActiveRecord: 0.0ms | Allocations: 2366)


Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:00 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 192.168.96.1 at 2023-08-09 12:40:01 +0900
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.6.1/lib/rails/templates/rails/welcome/index.html.erb (Duration: 17.7ms | Allocations: 178)
Completed 200 OK in 21ms (Views: 19.6ms | ActiveRecord: 0.0ms | Allocations: 730)


Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:01 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:02 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:05 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:10 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:19 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:40:36 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:41:09 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:42:14 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:44:23 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/ws" for 192.168.96.1 at 2023-08-09 12:48:40 +0900
  
ActionController::RoutingError (No route matches [GET] "/ws"):
  
actionpack (6.0.6.1) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.6.1) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.6.1) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.6.1) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.8) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.6.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.6.1) lib/action_dispatch/middleware/host_authorization.rb:103:in `call'
railties (6.0.6.1) lib/rails/engine.rb:527:in `call'
puma (4.3.12) lib/puma/configuration.rb:228:in `call'
puma (4.3.12) lib/puma/server.rb:727:in `handle_request'
puma (4.3.12) lib/puma/server.rb:476:in `process_client'
puma (4.3.12) lib/puma/server.rb:332:in `block in run'
puma (4.3.12) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
